#
# Copyright (c) 2012-2026 - @FabioZumbi12
#
# This class is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any
#  damages arising from the use of this class.
#
gui.flags.default.name=&e=> Flag-Name
gui.flags.default.description=&6Beschreibung: &aFlag-Beschreibung/n&amit Zeilenumbrüchen.
gui.flags.block-transform.name=&e=> Block-Verwandlung erlauben
gui.flags.block-transform.description=&6Beschreibung: &aErlaubt alle Block-/n&aVerwandlungen in dieser Region.
gui.flags.door.name=&e=> Tür öffnen erlauben
gui.flags.door.description=&6Beschreibung: &aErlaubt Nicht-Mitgliedern das/n&aÖffnen/Schließen von Türen.
gui.flags.smart-door.name=&e=> Doppeltüren und Eisentüren
gui.flags.smart-door.description=&6Beschreibung: &aErlaubt Mitgliedern das Öffnen/n&avon Türen und Eisenfalltüren.
gui.flags.pvp.name=&e=> PvP erlauben
gui.flags.pvp.description=&6Beschreibung: &aErlaubt PvP für alle Spieler/n&ain dieser Region.
gui.flags.allow-home.name=&e=> Home setzen erlauben
gui.flags.allow-home.description=&6Beschreibung: &aErlaubt Nicht-Mitgliedern/n&a/sethome oder /home hier zu nutzen.
gui.flags.chest.name=&e=> Kistenzugriff erlauben
gui.flags.chest.description=&6Beschreibung: &aErlaubt Nicht-Mitgliedern/n&aZugriff auf Kisten.
gui.flags.redstone.name=&e=> Redstone-Zugriff erlauben
gui.flags.redstone.description=&6Beschreibung: &aErlaubt Nicht-Mitgliedern/n&aRedstone zu nutzen und zu ändern.
gui.flags.lever.name=&e=> Hebel benutzen
gui.flags.lever.description=&6Beschreibung: &aErlaubt Nicht-Mitgliedern/n&adas Benutzen von Hebeln.
gui.flags.button.name=&e=> Knöpfe benutzen
gui.flags.button.description=&6Beschreibung: &aErlaubt Nicht-Mitgliedern/n&adas Benutzen von Knöpfen.
gui.flags.passives.name=&e=> Friedliche Mobs verletzen
gui.flags.passives.description=&6Beschreibung: &aErlaubt das Verletzen oder/n&aInteragieren mit friedlichen Mobs.
gui.flags.allow-magiccarpet.name=&e=> Magic Carpet erlauben
gui.flags.allow-magiccarpet.description=&6Beschreibung: &aErlaubt Magic Carpet/n&ain dieser Region.
gui.flags.minecart.name=&e=> Loren/Boote erlauben
gui.flags.minecart.description=&6Beschreibung: &aErlaubt das Platzieren und/n&aNutzen von Loren und Booten.
gui.flags.fire.name=&e=> Feuerausbreitung & Schaden
gui.flags.fire.description=&6Beschreibung: &aErlaubt Brandschaden,/n&aExplosionen und Feuerausbreitung.
gui.flags.flow.name=&e=> Wasser- und Lavafluss
gui.flags.flow.description=&6Beschreibung: &aAktiviert Wasser-/n&aund Lavafluss in dieser Region.
gui.flags.spawn-animals.name=&e=> Tiere spawnen
gui.flags.spawn-animals.description=&6Beschreibung: &aErlaubt natürliches/n&aSpawnen von Tieren hier.
gui.flags.spawn-monsters.name=&e=> Monster spawnen
gui.flags.spawn-monsters.description=&6Beschreibung: &aErlaubt natürliches/n&aSpawnen von Monstern hier.
gui.flags.use-potions.name=&e=> Tränke nutzen
gui.flags.use-potions.description=&6Beschreibung: &aErlaubt Nicht-Mitgliedern/n&adas Werfen/Nutzen von Tränken.
gui.flags.allow-effects.name=&e=> Effekte erlauben
gui.flags.allow-effects.description=&6Beschreibung: &aErlaubt Statuseffekte/n&afür Nicht-Mitglieder.
gui.flags.mob-loot.name=&e=> Mob-Griefing erlauben
gui.flags.mob-loot.description=&6Beschreibung: &aErlaubt Monstern das/n&aZerstören von Blöcken.
gui.flags.flow-damage.name=&e=> Flussschaden erlauben
gui.flags.flow-damage.description=&6Beschreibung: &aErlaubt Flüssigkeiten/n&adas Entfernen von Blöcken.
gui.flags.iceform-world.name=&e=> Eisbildung durch Welt
gui.flags.iceform-world.description=&6Beschreibung: &aErlaubt Eisbildung/n&adurch Schneemänner oder Wetter.
gui.flags.iceform-player.name=&e=> Eisbildung durch Spieler
gui.flags.iceform-player.description=&6Beschreibung: &aErlaubt Eisbildung durch/n&aFrostläufer-Verzauberung.
gui.flags.allow-fly.name=&e=> Fliegen erlauben
gui.flags.allow-fly.description=&6Beschreibung: &aErlaubt Spielern mit/n&aFlugmodus hier zu fliegen.
gui.flags.teleport.name=&e=> Teleportation erlauben
gui.flags.teleport.description=&6Beschreibung: &aErlaubt Teleportation mit/n&aEnderperlen und Chorusfrüchten.
gui.flags.clan.name=&e=> Clan-Region festlegen
gui.flags.clan.description=&6Beschreibung: &aSetzt Region als Clan-Heim/n&aund fügt alle Mitglieder hinzu.
gui.flags.ender-chest.name=&e=> Endertruhen-Zugriff
gui.flags.ender-chest.description=&6Beschreibung: &aErlaubt das Nutzen von/n&aEndertruhen in dieser Region.
gui.flags.can-grow.name=&e=> Pflanzenwachstum erlauben
gui.flags.can-grow.description=&bBeschreibung: &aWähle ob Pflanzen in/n&adiser Region wachsen oder nicht.
gui.flags.allow-spawner.name=&e=> Spawner abbauen/setzen
gui.flags.allow-spawner.description=&6Beschreibung: &aErlaubt Nicht-Mitgliedern/n&adas Setzen/Abbauen von Spawnern.
gui.flags.leaves-decay.name=&e=> Laubzerfall erlauben
gui.flags.leaves-decay.description=&6Beschreibung: &aErlaubt natürlichen/n&aLaubzerfall in der Region.
gui.flags.build.name=&e=> Bauen erlauben
gui.flags.build.description=&6Beschreibung: &aErlaubt Nicht-Mitgliedern/n&adas Platzieren/Abbauen von Blöcken.
gui.flags.gravity.name=&e=> Block-Schwerkraft erlauben
gui.flags.gravity.description=&6Beschreibung: &aErlaubt Schwerkraft/n&afür Blöcke (Kies, Sand usw.).
gui.flags.press-plate.name=&e=> Druckplatten erlauben
gui.flags.press-plate.description=&6Beschreibung: &aErlaubt Spielern das/n&aAuslösen von Druckplatten.
gui.flags.fishing.name=&e=> Angeln erlauben
gui.flags.fishing.description=&6Beschreibung: &aErlaubt Spielern das Angeln hier.
gui.strings.false=&cDeaktiviert
gui.strings.true=&aAktiviert
gui.strings.list=&e&l> Öffnen
gui.strings.value=&bStatus:
gui.strings.separator=&7|
gui.flags.can-back.name=&e=> /back erlauben
gui.flags.can-back.description=&6Beschreibung: &aErlaubt Spielern den Befehl/n&a/back in diese Region zu nutzen.
gui.flags.can-pet.name=&e=> Haustiere erlauben
gui.flags.can-pet.description=&6Beschreibung: &aErlaubt Spielern das/n&aNutzen von Haustieren hier.
