#
# Copyright (c) 2012-2026 - @FabioZumbi12
#
# This class is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any
#  damages arising from the use of this class.
#
gui.flags.default.name=&e=> Nom du Flag
gui.flags.default.description=&6Description: &aDescription du flag/n&aavec retours à la ligne.
gui.flags.block-transform.name=&e=> Transformation de Blocs
gui.flags.block-transform.description=&6Description: &aAutoriser les transformations/n&ade blocs dans cette région.
gui.flags.door.name=&e=> Ouvrir les Portes
gui.flags.door.description=&6Description: &aAutoriser les non-membres/n&aà ouvrir/fermer les portes.
gui.flags.smart-door.name=&e=> Portes Doubles et en Fer
gui.flags.smart-door.description=&6Description: &aAutoriser les membres à ouvrir/n&aportes simples, doubles et trappes en fer.
gui.flags.pvp.name=&e=> Autoriser le PvP
gui.flags.pvp.description=&6Description: &aAutoriser le PvP pour tous/n&adans cette région.
gui.flags.allow-home.name=&e=> Autoriser /sethome
gui.flags.allow-home.description=&6Description: &aAutoriser les non-membres/n&aà utiliser /home ou /sethome ici.
gui.flags.chest.name=&e=> Accès aux Coffres
gui.flags.chest.description=&6Description: &aAutoriser les non-membres/n&aà ouvrir les coffres.
gui.flags.redstone.name=&e=> Accès Redstone
gui.flags.redstone.description=&6Description: &aAutoriser les non-membres/n&aà utiliser les circuits de redstone.
gui.flags.lever.name=&e=> Utiliser les Leviers
gui.flags.lever.description=&6Description: &aAutoriser les non-membres/n&aà utiliser les leviers.
gui.flags.button.name=&e=> Utiliser les Boutons
gui.flags.button.description=&6Description: &aAutoriser les non-membres/n&aà utiliser les boutons.
gui.flags.passives.name=&e=> Frapper Mobs Passifs
gui.flags.passives.description=&6Description: &aAutoriser à frapper ou/n&ainteragir avec les mobs passifs.
gui.flags.allow-magiccarpet.name=&e=> Magic Carpet
gui.flags.allow-magiccarpet.description=&6Description: &aAutoriser Magic Carpet/n&adans cette région.
gui.flags.minecart.name=&e=> Wagons et Bateaux
gui.flags.minecart.description=&6Description: &aAutoriser à poser et utiliser/n&ades wagons et bateaux.
gui.flags.fire.name=&e=> Propagation du Feu
gui.flags.fire.description=&6Description: &aAutoriser les dégâts de feu,/n&aexplosions et propagation.
gui.flags.flow.name=&e=> Écoulement Eau/Lave
gui.flags.flow.description=&6Description: &aActiver l'écoulement de/n&al'eau et de la lave.
gui.flags.spawn-animals.name=&e=> Apparition Animaux
gui.flags.spawn-animals.description=&6Description: &aAutoriser l'apparition/n&anaturelle des animaux.
gui.flags.spawn-monsters.name=&e=> Apparition Monstres
gui.flags.spawn-monsters.description=&6Description: &aAutoriser l'apparition/n&anaturelle des monstres.
gui.flags.use-potions.name=&e=> Utiliser Potions
gui.flags.use-potions.description=&6Description: &aAutoriser les non-membres/n&aà lancer des potions.
gui.flags.allow-effects.name=&e=> Autoriser Effets
gui.flags.allow-effects.description=&6Description: &aAutoriser tous types/n&ad'effets pour les non-membres.
gui.flags.mob-loot.name=&e=> Grief de Mobs
gui.flags.mob-loot.description=&6Description: &aAutoriser les monstres à/n&aexploser ou détruire des blocs.
gui.flags.flow-damage.name=&e=> Dégâts des Liquides
gui.flags.flow-damage.description=&6Description: &aAutoriser les liquides à/n&adétruire des blocs en coulant.
gui.flags.iceform-world.name=&e=> Gel par le Monde
gui.flags.iceform-world.description=&6Description: &aAutoriser la formation de/n&aglace par météo ou bonhomme de neige.
gui.flags.iceform-player.name=&e=> Gel par les Joueurs
gui.flags.iceform-player.description=&6Description: &aAutoriser la formation de glace/n&avia l'enchantement Semelles givrantes.
gui.flags.allow-fly.name=&e=> Autoriser le Vol
gui.flags.allow-fly.description=&6Description: &aAutoriser les joueurs en vol/n&aà voler dans cette région.
gui.flags.teleport.name=&e=> Téléportation
gui.flags.teleport.description=&6Description: &aAutoriser la téléportation/n&avia perles de l'Ender et fruits de chorus.
gui.flags.clan.name=&e=> Région de Clan
gui.flags.clan.description=&6Description: &aDéfinir comme région de clan/n&aet ajouter tous les membres.
gui.flags.ender-chest.name=&e=> Coffres du Néant
gui.flags.ender-chest.description=&6Description: &aAutoriser l'accès aux/n&acoffres du Néant (EnderChest).
gui.flags.can-grow.name=&e=> Croissance des Cultures
gui.flags.can-grow.description=&bDescription: &aDéfinir si les cultures/n&apoussent dans cette région.
gui.flags.allow-spawner.name=&e=> Générateurs de Mobs
gui.flags.allow-spawner.description=&6Description: &aAutoriser les non-membres/n&aà poser ou casser des générateurs.
gui.flags.leaves-decay.name=&e=> Disparition des Feuilles
gui.flags.leaves-decay.description=&6Description: &aAutoriser la disparition/n&anaturelle des feuilles.
gui.flags.build.name=&e=> Construire
gui.flags.build.description=&6Description: &aAutoriser les non-membres/n&aà poser et casser des blocs.
gui.flags.gravity.name=&e=> Gravité des Blocs
gui.flags.gravity.description=&6Description: &aPermettre la gravité/n&asur les blocs (sable, gravier).
gui.flags.press-plate.name=&e=> Plaques de Pression
gui.flags.press-plate.description=&6Description: &aAutoriser les joueurs/n&aà activer les plaques de pression.
gui.flags.fishing.name=&e=> Pêcher
gui.flags.fishing.description=&6Description: &aAutoriser les joueurs à pêcher ici.
gui.strings.false=&cFaux
gui.strings.true=&aVrai
gui.strings.list=&e&l> Ouvrir
gui.strings.value=&bStatut:
gui.strings.separator=&7|
gui.flags.can-back.name=&e=> Autoriser /back
gui.flags.can-back.description=&6Description: &aAutoriser les joueurs à/n&arevenir ici avec /back.
gui.flags.can-pet.name=&e=> Autoriser Familiers
gui.flags.can-pet.description=&6Description: &aAutoriser les familiers/n&adans cette région.
