#
# Copyright (c) 2012-2026 - @FabioZumbi12
#
# This class is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any
#  damages arising from the use of this class.
#
gui.flags.default.name=&e=> Nome Flag
gui.flags.default.description=&6Descrizione: &aDescrizione flag/n&acon interruzioni di riga.
gui.flags.block-transform.name=&e=> Trasformazione Blocchi
gui.flags.block-transform.description=&6Descrizione: &aPermetti tutte le/n&atrasformazioni blocchi nella regione.
gui.flags.door.name=&e=> Apri Porte
gui.flags.door.description=&6Descrizione: &aPermetti ai non membri/n&adi aprire e chiudere le porte.
gui.flags.smart-door.name=&e=> Porte Doppie e di Ferro
gui.flags.smart-door.description=&6Descrizione: &aPermetti ai membri di aprire/n&aporte singole, doppie e botole di ferro.
gui.flags.pvp.name=&e=> Abilita PvP
gui.flags.pvp.description=&6Descrizione: &aAbilita PvP per tutti/n&ai giocatori in questa regione.
gui.flags.allow-home.name=&e=> Abilita /sethome
gui.flags.allow-home.description=&6Descrizione: &aPermetti ai non membri di/n&ausare /sethome o /home qui.
gui.flags.chest.name=&e=> Accesso Casse
gui.flags.chest.description=&6Descrizione: &aPermetti ai non membri/n&adi accedere alle casse.
gui.flags.redstone.name=&e=> Accesso Redstone
gui.flags.redstone.description=&6Descrizione: &aPermetti ai non membri di/n&ausare circuiti di redstone.
gui.flags.lever.name=&e=> Usa Leve
gui.flags.lever.description=&6Descrizione: &aPermetti ai non membri di/n&aattivare le leve.
gui.flags.button.name=&e=> Usa Pulsanti
gui.flags.button.description=&6Descrizione: &aPermetti ai non membri di/n&apremere i pulsanti.
gui.flags.passives.name=&e=> Colpisci Passivi
gui.flags.passives.description=&6Descrizione: &aPermetti ai non membri di/n&adanneggiare mob passivi.
gui.flags.allow-magiccarpet.name=&e=> Magic Carpet
gui.flags.allow-magiccarpet.description=&6Descrizione: &aPermetti Magic Carpet/n&ain questa regione.
gui.flags.minecart.name=&e=> Carrelli e Barche
gui.flags.minecart.description=&6Descrizione: &aPermetti di piazzare/n&ae usare carrelli e barche.
gui.flags.fire.name=&e=> Propagazione Fuoco
gui.flags.fire.description=&6Descrizione: &aPermetti propagazione fuoco/n&ae danni da esplosioni.
gui.flags.flow.name=&e=> Flusso Acqua/Lava
gui.flags.flow.description=&6Descrizione: &aAbilita flusso di acqua/n&ae lava in questa regione.
gui.flags.spawn-animals.name=&e=> Genera Animali
gui.flags.spawn-animals.description=&6Descrizione: &aPermetti generazione naturale/n&adi animali in questa regione.
gui.flags.spawn-monsters.name=&e=> Genera Mostri
gui.flags.spawn-monsters.description=&6Descrizione: &aPermetti generazione naturale/n&adi mostri in questa regione.
gui.flags.use-potions.name=&e=> Usa Pozioni
gui.flags.use-potions.description=&6Descrizione: &aPermetti ai non membri di/n&alanciare o usare pozioni.
gui.flags.allow-effects.name=&e=> Abilita Effetti
gui.flags.allow-effects.description=&6Descrizione: &aPermetti o annulla/n&atutti gli effetti per non membri.
gui.flags.mob-loot.name=&e=> Griefing dei Mob
gui.flags.mob-loot.description=&6Descrizione: &aPermetti ai mob di danneggiare/n&ao distruggere blocchi.
gui.flags.flow-damage.name=&e=> Danni da Flusso
gui.flags.flow-damage.description=&6Descrizione: &aPermetti ai liquidi di/n&arimuovere blocchi durante il flusso.
gui.flags.iceform-world.name=&e=> Formazione Ghiaccio (Mondo)
gui.flags.iceform-world.description=&6Descrizione: &aPermetti formazione ghiaccio/n&ada pupazzi di neve o meteo.
gui.flags.iceform-player.name=&e=> Formazione Ghiaccio (Player)
gui.flags.iceform-player.description=&6Descrizione: &aPermetti formazione ghiaccio/n&acon incantesimo Passo Gelido.
gui.flags.allow-fly.name=&e=> Abilita Volo
gui.flags.allow-fly.description=&6Descrizione: &aPermetti il volo ai/n&agiocatori in questa regione.
gui.flags.teleport.name=&e=> Abilita Teletrasporto
gui.flags.teleport.description=&6Descrizione: &aPermetti teletrasporto usando/n&aperle di ender o frutti del chorus.
gui.flags.clan.name=&e=> Imposta Regione Clan
gui.flags.clan.description=&6Descrizione: &aImposta regione come casa clan,/n&aaggiungendo tutti i membri.
gui.flags.ender-chest.name=&e=> Accesso EnderChest
gui.flags.ender-chest.description=&6Descrizione: &aPermetti ai giocatori di/n&ausare casse di ender qui.
gui.flags.can-grow.name=&e=> Crescita Coltivazioni
gui.flags.can-grow.description=&bDescrizione: &aScegli se le coltivazioni/n&acresceranno in questa regione.
gui.flags.allow-spawner.name=&e=> Spawner Mob
gui.flags.allow-spawner.description=&6Descrizione: &aPermetti ai non membri/n&adi piazzare o rompere spawner.
gui.flags.leaves-decay.name=&e=> Decadimento Foglie
gui.flags.leaves-decay.description=&6Descrizione: &aPermetti il decadimento/n&anaturale delle foglie.
gui.flags.build.name=&e=> Costruisci
gui.flags.build.description=&6Descrizione: &aPermetti ai non membri di/n&apiazzare e rompere blocchi.
gui.flags.gravity.name=&e=> Gravità Blocchi
gui.flags.gravity.description=&6Descrizione: &aPermetti gravità/n&asui blocchi (sabbia, ghiaia).
gui.flags.press-plate.name=&e=> Piastre a Pressione
gui.flags.press-plate.description=&6Descrizione: &aPermetti ai giocatori di/n&aattivare piastre a pressione.
gui.flags.fishing.name=&e=> Pesca
gui.flags.fishing.description=&6Descrizione: &aPermetti ai giocatori di pescare qui.
gui.strings.false=&cFalso
gui.strings.true=&aVero
gui.strings.list=&e&l> Apri
gui.strings.value=&bStato:
gui.strings.separator=&7|
gui.flags.can-back.name=&e=> Permetti /back
gui.flags.can-back.description=&6Descrizione: &aPermetti ai giocatori di usare/n&a/back per tornare in questa regione.
gui.flags.can-pet.name=&e=> Permetti Animali Domestici
gui.flags.can-pet.description=&6Descrizione: &aPermetti ai giocatori di/n&aportare animali domestici qui.
