#
# Copyright (c) 2012-2026 - @FabioZumbi12
#
# This class is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any
#  damages arising from the use of this class.
#
gui.flags.default.name=&e=> フラグ名
gui.flags.default.description=&6説明: &aフラグの説明/n&a（改行あり）。
gui.flags.block-transform.name=&e=> ブロックの変形を許可
gui.flags.block-transform.description=&6説明: &aこの保護領域内での/n&aすべてのブロック変化を許可します。
gui.flags.door.name=&e=> ドアの開閉を許可
gui.flags.door.description=&6説明: &aメンバー以外のプレイヤーが/n&aドアを開閉することを許可します。
gui.flags.smart-door.name=&e=> 二重ドア・鉄のドア
gui.flags.smart-door.description=&6説明: &aメンバーが鉄のドアやトラップドア、/n&a二重ドアを開くことを許可します。
gui.flags.pvp.name=&e=> PvPを許可
gui.flags.pvp.description=&6説明: &aこの領域内のすべてのプレイヤー間で/n&aPvPを許可します。
gui.flags.allow-home.name=&e=> 拠点の設置を許可
gui.flags.allow-home.description=&6説明: &a非メンバーが/sethomeや/homeで/n&aここに来ることを許可します。
gui.flags.chest.name=&e=> チェストのアクセス
gui.flags.chest.description=&6説明: &a非メンバーがチェストを開けて/n&aアイテムを出し入れすることを許可します。
gui.flags.redstone.name=&e=> レッドストーンの操作
gui.flags.redstone.description=&6説明: &a非メンバーがレッドストーン回路/n&aを操作することを許可します。
gui.flags.lever.name=&e=> レバーの使用
gui.flags.lever.description=&6説明: &a非メンバーがレバーを使用/n&aすることを許可します。
gui.flags.button.name=&e=> ボタンの使用
gui.flags.button.description=&6説明: &a非メンバーがボタンを押す/n&aことを許可します。
gui.flags.passives.name=&e=> 友好モブへの攻撃
gui.flags.passives.description=&6説明: &a非メンバーが友好モブを攻撃・/n&a触れることを許可します。
gui.flags.allow-magiccarpet.name=&e=> マジックカーペット
gui.flags.allow-magiccarpet.description=&6説明: &aこの保護領域内でマジック/n&aカーペットの使用を許可します。
gui.flags.minecart.name=&e=> トロッコ・ボート
gui.flags.minecart.description=&6説明: &a非メンバーがトロッコやボート/n&aを設置・使用することを許可します。
gui.flags.fire.name=&e=> 火の延焼とダメージ
gui.flags.fire.description=&6説明: &a火によるブロック被害、爆発、/n&a延焼を許可します。
gui.flags.flow.name=&e=> 水・溶岩の流れ
gui.flags.flow.description=&6説明: &aこの保護領域内で水や溶岩/n&aが流れることを許可します。
gui.flags.spawn-animals.name=&e=> 動物のスポーン
gui.flags.spawn-animals.description=&6説明: &aこの領域内で自然に動物が/n&aスポーンすることを許可します。
gui.flags.spawn-monsters.name=&e=> モンスターのスポーン
gui.flags.spawn-monsters.description=&6説明: &aこの領域内で自然にモンスターが/n&aスポーンすることを許可します。
gui.flags.use-potions.name=&e=> ポーションの使用
gui.flags.use-potions.description=&6説明: &a非メンバーがポーションを投げる・/n&a使用することを許可します。
gui.flags.allow-effects.name=&e=> ステータス効果
gui.flags.allow-effects.description=&6説明: &a非メンバーに対するすべての/n&aステータス効果を許可します。
gui.flags.mob-loot.name=&e=> モブによる破壊
gui.flags.mob-loot.description=&6説明: &aモブがブロックを破壊・爆発/n&aさせることを許可します。
gui.flags.flow-damage.name=&e=> 流体による破壊
gui.flags.flow-damage.description=&6説明: &a水や溶岩の流れによって/n&aブロックが流されることを許可します。
gui.flags.iceform-world.name=&e=> 氷の生成（自然）
gui.flags.iceform-world.description=&6説明: &a天候やスノーゴーレムによる/n&a氷・雪の生成を許可します。
gui.flags.iceform-player.name=&e=> 氷の生成（プレイヤー）
gui.flags.iceform-player.description=&6説明: &a氷渡りエンチャントによる/n&a氷の生成を許可します。
gui.flags.allow-fly.name=&e=> 飛行を許可
gui.flags.allow-fly.description=&6説明: &a飛行可能なプレイヤーが/n&aこの領域で飛ぶことを許可します。
gui.flags.teleport.name=&e=> テレポートを許可
gui.flags.teleport.description=&6説明: &aエンダーパールやコーラスフルーツ/n&aによるテレポートを許可します。
gui.flags.clan.name=&e=> クラン領域に設定
gui.flags.clan.description=&6説明: &aこの領域をクラン拠点として設定し、/n&a全クランメンバーを追加します。
gui.flags.ender-chest.name=&e=> エンダーチェスト
gui.flags.ender-chest.description=&6説明: &aこの領域でエンダーチェストの/n&a使用を許可します。
gui.flags.can-grow.name=&e=> 作物の成長
gui.flags.can-grow.description=&b説明: &aこの領域内で農作物が/n&a成長するかどうかを設定します。
gui.flags.allow-spawner.name=&e=> スポナーの設置・破壊
gui.flags.allow-spawner.description=&6説明: &a非メンバーがモブスポナーを/n&a設置・破壊することを許可します。
gui.flags.leaves-decay.name=&e=> 葉の自然消滅
gui.flags.leaves-decay.description=&6説明: &a葉ブロックが自然に消滅する/n&aことを許可します。
gui.flags.build.name=&e=> 建築を許可
gui.flags.build.description=&6説明: &a非メンバーがブロックを設置・/n&a破壊することを許可します。
gui.flags.gravity.name=&e=> ブロックの重力
gui.flags.gravity.description=&6説明: &a砂や砂利などのブロックの/n&a重力落下を許可します。
gui.flags.press-plate.name=&e=> 感圧板の作動
gui.flags.press-plate.description=&6説明: &aプレイヤーが感圧板を/n&a作動させることを許可します。
gui.flags.fishing.name=&e=> 釣りを許可
gui.flags.fishing.description=&6説明: &aプレイヤーがここで釣りをすることを許可します。
gui.strings.false=&c無効
gui.strings.true=&a有効
gui.strings.list=&e&l> 開く
gui.strings.value=&b状態:
gui.strings.separator=&7|
gui.flags.can-back.name=&e=> /backを許可
gui.flags.can-back.description=&6説明: &aプレイヤーが/backコマンドで/n&aこの領域に戻ることを許可します。
gui.flags.can-pet.name=&e=> ペットの立ち入り
gui.flags.can-pet.description=&6説明: &aプレイヤーがペットを連れて/n&aこの領域に入ることを許可します。
