#
# Copyright (c) 2012-2026 - @FabioZumbi12
#
# This class is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any
#  damages arising from the use of this class.
#
gui.flags.default.name=&e=> 플래그 이름
gui.flags.default.description=&6설명: &a줄바꿈이 포함된/n&a플래그 설명입니다.
gui.flags.block-transform.name=&e=> 블록 변형 허용
gui.flags.block-transform.description=&6설명: &a이 구역에서 모든 블록의/n&a변형을 허용합니다.
gui.flags.door.name=&e=> 문 열기 허용
gui.flags.door.description=&6설명: &a비멤버가 문을 열고 닫는/n&a것을 허용합니다.
gui.flags.smart-door.name=&e=> 이중문 및 철문
gui.flags.smart-door.description=&6설명: &a멤버가 철문 및 이중문을/n&a여는 것을 허용합니다.
gui.flags.pvp.name=&e=> PvP 허용
gui.flags.pvp.description=&6설명: &a이 구역 내의 모든 플레이어 간/n&aPvP를 허용합니다.
gui.flags.allow-home.name=&e=> 홈 설정 허용
gui.flags.allow-home.description=&6설명: &a비멤버가 /sethome 또는 /home으로/n&a이 구역에 오는 것을 허용합니다.
gui.flags.chest.name=&e=> 상자 접근 허용
gui.flags.chest.description=&6설명: &a비멤버가 상자를 열고/n&a아이템을 꺼내는 것을 허용합니다.
gui.flags.redstone.name=&e=> 레드스톤 조작
gui.flags.redstone.description=&6설명: &a비멤버가 레드스톤 장치를/n&a조작하는 것을 허용합니다.
gui.flags.lever.name=&e=> 레버 조작
gui.flags.lever.description=&6설명: &a비멤버가 레버를 조작하는/n&a것을 허용합니다.
gui.flags.button.name=&e=> 버튼 조작
gui.flags.button.description=&6설명: &a비멤버가 버튼을 누르는/n&a것을 허용합니다.
gui.flags.passives.name=&e=> 평화로운 몹 공격
gui.flags.passives.description=&6설명: &a평화로운 동물/몹을 공격하거나/n&a상호작용하는 것을 허용합니다.
gui.flags.allow-magiccarpet.name=&e=> 매직 카펫 허용
gui.flags.allow-magiccarpet.description=&6설명: &a이 구역에서 매직 카펫/n&a사용을 허용합니다.
gui.flags.minecart.name=&e=> 카트 및 보트 허용
gui.flags.minecart.description=&6설명: &a카트 및 보트를 설치하고/n&a탑승하는 것을 허용합니다.
gui.flags.fire.name=&e=> 불 번짐 및 피해
gui.flags.fire.description=&6설명: &a불 번짐, 폭발 및 화재/n&a피해를 허용합니다.
gui.flags.flow.name=&e=> 물 및 용암 흐름
gui.flags.flow.description=&6설명: &a이 구역에서 물과 용암이/n&a흐르는 것을 활성화합니다.
gui.flags.spawn-animals.name=&e=> 동물 스폰 허용
gui.flags.spawn-animals.description=&6설명: &a이 구역에서 자연스러운/n&a동물 생성을 허용합니다.
gui.flags.spawn-monsters.name=&e=> 몬스터 스폰 허용
gui.flags.spawn-monsters.description=&6설명: &a이 구역에서 자연스러운/n&a몬스터 생성을 허용합니다.
gui.flags.use-potions.name=&e=> 포션 사용 허용
gui.flags.use-potions.description=&6설명: &a비멤버가 포션을 던지거나/n&a사용하는 것을 허용합니다.
gui.flags.allow-effects.name=&e=> 효과 허용
gui.flags.allow-effects.description=&6설명: &a비멤버에게 모든 상태/n&a효과를 허용합니다.
gui.flags.mob-loot.name=&e=> 몹에 의한 파괴
gui.flags.mob-loot.description=&6설명: &a몬스터가 블록을 파괴하거나/n&a폭발시키는 것을 허용합니다.
gui.flags.flow-damage.name=&e=> 유체 블록 파괴
gui.flags.flow-damage.description=&6설명: &a물이 흐르며 블록을/n&a부수는 것을 허용합니다.
gui.flags.iceform-world.name=&e=> 얼음 생성 (월드)
gui.flags.iceform-world.description=&6설명: &a날씨나 눈사람에 의해/n&a얼음이 어는 것을 허용합니다.
gui.flags.iceform-player.name=&e=> 얼음 생성 (플레이어)
gui.flags.iceform-player.description=&6설명: &a차가운 걸음 마법으로/n&a얼음이 어는 것을 허용합니다.
gui.flags.allow-fly.name=&e=> 비행 허용
gui.flags.allow-fly.description=&6설명: &a비행 기능이 있는 플레이어의/n&a비행을 허용합니다.
gui.flags.teleport.name=&e=> 텔레포트 허용
gui.flags.teleport.description=&6설명: &a엔더 진주나 코러스 열매로/n&a순간이동하는 것을 허용합니다.
gui.flags.clan.name=&e=> 클랜 구역 설정
gui.flags.clan.description=&6설명: &a이 구역을 클랜 홈으로 설정하고/n&a모든 멤버를 추가합니다.
gui.flags.ender-chest.name=&e=> 엔더 상자 접근
gui.flags.ender-chest.description=&6설명: &a플레이어가 엔더 상자를/n&a사용하는 것을 허용합니다.
gui.flags.can-grow.name=&e=> 작물 성장
gui.flags.can-grow.description=&b설명: &a이 구역에서 작물이/n&a자라도록 할지 선택합니다.
gui.flags.allow-spawner.name=&e=> 스포너 설치/파괴
gui.flags.allow-spawner.description=&6설명: &a비멤버가 몹 스포너를/n&a설치하거나 파괴하는 것을 허용합니다.
gui.flags.leaves-decay.name=&e=> 나뭇잎 자연 소멸
gui.flags.leaves-decay.description=&6설명: &a나뭇잎이 자연적으로/n&a사라지는 것을 허용합니다.
gui.flags.build.name=&e=> 건축 허용
gui.flags.build.description=&6설명: &a비멤버가 블록을 설치하고/n&a파괴하는 것을 허용합니다.
gui.flags.gravity.name=&e=> 블록 중력
gui.flags.gravity.description=&6설명: &a모래나 자갈 등의 블록에/n&a중력이 작용하도록 허용합니다.
gui.flags.press-plate.name=&e=> 압력판 작동
gui.flags.press-plate.description=&6설명: &a플레이어가 압력판을/n&a작동시키는 것을 허용합니다.
gui.flags.fishing.name=&e=> 낚시 허용
gui.flags.fishing.description=&6설명: &a플레이어가 여기서 낚시하는 것을 허용합니다.
gui.strings.false=&c비활성화
gui.strings.true=&a활성화
gui.strings.list=&e&l> 열기
gui.strings.value=&b상태:
gui.strings.separator=&7|
gui.flags.can-back.name=&e=> /back 사용 허용
gui.flags.can-back.description=&6설명: &a플레이어가 /back 명령어로/n&a이 구역에 돌아오는 것을 허용합니다.
gui.flags.can-pet.name=&e=> 펫 동반 허용
gui.flags.can-pet.description=&6설명: &a플레이어가 펫을 데리고/n&a이 구역에 들어오는 것을 허용합니다.
