#
# Copyright (c) 2012-2026 - @FabioZumbi12
#
# This class is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any
#  damages arising from the use of this class.
#
gui.flags.default.name=&e=> Bayrak Adı
gui.flags.default.description=&6Açıklama: &aBayrak açıklaması/n&asatır sonlarıyla.
gui.flags.block-transform.name=&e=> Blok Dönüşümüne İzin Ver
gui.flags.block-transform.description=&6Açıklama: &aBu bölgede tüm blok/n&adönüşümlerine izin verir.
gui.flags.door.name=&e=> Kapı Açmaya İzin Ver
gui.flags.door.description=&6Açıklama: &aÜye olmayanların kapı/n&aaçıp kapatmasına izin verir.
gui.flags.smart-door.name=&e=> Çift ve Demir Kapılar
gui.flags.smart-door.description=&6Açıklama: &aÜyelerin demir ve çift/n&akapıları açmasına izin verir.
gui.flags.pvp.name=&e=> PvP'ye İzin Ver
gui.flags.pvp.description=&6Açıklama: &aBu bölgedeki tüm oyuncular/n&aiçin PvP'yi etkinleştirir.
gui.flags.allow-home.name=&e=> Ev Belirlemeye İzin Ver
gui.flags.allow-home.description=&6Açıklama: &aÜye olmayanların burada/n&a/sethome veya /home kullanmasına izin verir.
gui.flags.chest.name=&e=> Sandık Erişimi
gui.flags.chest.description=&6Açıklama: &aÜye olmayanların sandıklara/n&aerişmesine izin verir.
gui.flags.redstone.name=&e=> Kızıltaş Erişimi
gui.flags.redstone.description=&6Açıklama: &aÜye olmayanların kızıltaş/n&asistemlerini kullanmasına izin verir.
gui.flags.lever.name=&e=> Şalter Kullanımı
gui.flags.lever.description=&6Açıklama: &aÜye olmayanların şalter/n&akullanmasına izin verir.
gui.flags.button.name=&e=> Düğme Kullanımı
gui.flags.button.description=&6Açıklama: &aÜye olmayanların düğme/n&akullanmasına izin verir.
gui.flags.passives.name=&e=> Pasif Canlılara Vurma
gui.flags.passives.description=&6Açıklama: &aPasif canlılara saldırmaya/n&aveya etkileşime izin verir.
gui.flags.allow-magiccarpet.name=&e=> Sihirli Halı
gui.flags.allow-magiccarpet.description=&6Açıklama: &aBu bölgede Sihirli Halı/n&akullanımına izin verir.
gui.flags.minecart.name=&e=> Vagon ve Tekneler
gui.flags.minecart.description=&6Açıklama: &aVagon ve tekne koymaya/n&ave binmeye izin verir.
gui.flags.fire.name=&e=> Yangın Yayılması
gui.flags.fire.description=&6Açıklama: &aAteş yayılması ve blok/n&ahasarına izin verir.
gui.flags.flow.name=&e=> Su ve Lav Akıntısı
gui.flags.flow.description=&6Açıklama: &aBu bölgede su ve lav/n&aakıntısını etkinleştirir.
gui.flags.spawn-animals.name=&e=> Hayvan Doğması
gui.flags.spawn-animals.description=&6Açıklama: &aBu bölgede doğal hayvan/n&adoğmasına izin verir.
gui.flags.spawn-monsters.name=&e=> Canavar Doğması
gui.flags.spawn-monsters.description=&6Açıklama: &aBu bölgede doğal canavar/n&adoğmasına izin verir.
gui.flags.use-potions.name=&e=> İksir Kullanımı
gui.flags.use-potions.description=&6Açıklama: &aÜye olmayanların iksir/n&akullanmasına izin verir.
gui.flags.allow-effects.name=&e=> Efektlere İzin Ver
gui.flags.allow-effects.description=&6Açıklama: &aÜye olmayanlar için/n&atüm efektleri etkinleştirir.
gui.flags.mob-loot.name=&e=> Yaratık Hasarı (Grief)
gui.flags.mob-loot.description=&6Açıklama: &aYaratıkların blokları/n&apatlatmasına izin verir.
gui.flags.flow-damage.name=&e=> Akıntı Hasarı
gui.flags.flow-damage.description=&6Açıklama: &aSıvıların akarken blokları/n&akırmasına izin verir.
gui.flags.iceform-world.name=&e=> Buz Oluşumu (Dünya)
gui.flags.iceform-world.description=&6Açıklama: &aHava durumu veya Kardan Adam/n&atarafından buz oluşumuna izin verir.
gui.flags.iceform-player.name=&e=> Buz Oluşumu (Oyuncu)
gui.flags.iceform-player.description=&6Açıklama: &aDonmuş Adım büyüsüyle/n&abuz oluşumuna izin verir.
gui.flags.allow-fly.name=&e=> Uçmaya İzin Ver
gui.flags.allow-fly.description=&6Açıklama: &aOyuncuların bu bölgede/n&auçmasına izin verir.
gui.flags.teleport.name=&e=> Işınlanmaya İzin Ver
gui.flags.teleport.description=&6Açıklama: &aEnder incisi ve Koro meyvesiyle/n&aışınlanmaya izin verir.
gui.flags.clan.name=&e=> Klan Bölgesi Belirle
gui.flags.clan.description=&6Açıklama: &aBölgeyi klan evi yapar ve/n&atüm üyeleri ekler.
gui.flags.ender-chest.name=&e=> Ender Sandığı Erişimi
gui.flags.ender-chest.description=&6Açıklama: &aOyuncuların Ender sandığı/n&akullanmasına izin verir.
gui.flags.can-grow.name=&e=> Ekin Büyümesi
gui.flags.can-grow.description=&bAçıklama: &aBu bölgede tarım ürünlerinin/n&abüyüyüp büyümeyeceğini seçin.
gui.flags.allow-spawner.name=&e=> Canavar Doğurucu (Spawner)
gui.flags.allow-spawner.description=&6Açıklama: &aÜye olmayanların spawner/n&akoymasına veya kırmasına izin verir.
gui.flags.leaves-decay.name=&e=> Yaprak Dökülmesi
gui.flags.leaves-decay.description=&6Açıklama: &aYaprakların doğal olarak/n&adökülmesine izin verir.
gui.flags.build.name=&e=> İnşa Etme
gui.flags.build.description=&6Açıklama: &aÜye olmayanların blok/n&akoymasına ve kırmasına izin verir.
gui.flags.gravity.name=&e=> Blok Yerçekimi
gui.flags.gravity.description=&6Açıklama: &aBlokların yerçekimine/n&asahip olmasına izin verir.
gui.flags.press-plate.name=&e=> Basınç Plakaları
gui.flags.press-plate.description=&6Açıklama: &aOyuncuların basınç plakası/n&aetkinleştirmesine izin verir.
gui.flags.fishing.name=&e=> Balık Tutma
gui.flags.fishing.description=&6Açıklama: &aOyuncuların burada balık tutmasına izin verir.
gui.strings.false=&cKapalı
gui.strings.true=&aAçık
gui.strings.list=&e&l> Aç
gui.strings.value=&bDurum:
gui.strings.separator=&7|
gui.flags.can-back.name=&e=> /back Komutuna İzin Ver
gui.flags.can-back.description=&6Açıklama: &aOyuncuların bu bölgeye /back/n&aile dönmesine izin verir.
gui.flags.can-pet.name=&e=> Evcil Hayvanlara İzin Ver
gui.flags.can-pet.description=&6Açıklama: &aOyuncuların burada evcil/n&ahayvan kullanmasına izin verir.
