#
# Copyright (c) 2012-2026 - @FabioZumbi12
#
# This class is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any
#  damages arising from the use of this class.
#
gui.flags.default.name=&e\=> Flag Name
gui.flags.default.description=&6Description\: &aFlag description/n&awith line breaks.
gui.flags.block-transform.name=&e=> Allow Block Transform
gui.flags.block-transform.description=&6Description: &aAllow all block transforms/n&ain this region.
gui.flags.door.name=&e\=> 允許開門
gui.flags.door.description=&6描述： &a允許玩家在该區域内/n&a控制門的開關/n
gui.flags.smart-door.name=&e\=> 打開双門或鐵門
gui.flags.smart-door.description=&6描述： &a允許在此區域内的玩家/n&a打開双門或鐵門/n
gui.flags.pvp.name=&e\=> 允許PvP
gui.flags.pvp.description=&6描述： &a允許在此區域内的玩家/n&a進行pvp/n
gui.flags.allow-home.name=&e\=> 允許置家
gui.flags.allow-home.description=&6描述： &a允許玩家使用/n&a命令 /sethome 或 /home 来置家/n&a以便傳送到這裡
gui.flags.chest.name=&e\=> 允許使用箱子
gui.flags.chest.description=&6描述： &a允許玩家在该區域内/n&a使用箱子/n
gui.flags.redstone.name=&e=> Allow Redstone Access
gui.flags.redstone.description=&6Description: &aAllow non-members to access/n&aredstone systems and change redstone blocks.
gui.flags.lever.name=&e\=> 允許使用拉桿
gui.flags.lever.description=&6描述： &a允許在此區域内的玩家/n&a使用拉桿/n
gui.flags.button.name=&e\=> 允許按下按鈕
gui.flags.button.description=&6描述： &a允許玩家在此區域内/n&a按下按鈕/n
gui.flags.passives.name=&e\=> 攻擊/使用可骑行生物
gui.flags.passives.description=&6描述： &a禁止所有玩家/n&a伤害或骑行在此區域内的/n&a可骑行生物
gui.flags.allow-magiccarpet.name=&e\=> Allow Magic Carpet
gui.flags.allow-magiccarpet.description=&6Description\: &aAllow players walk with/n&aMagic Carpet in your region
gui.flags.minecart.name=&e\=> 允許放置矿车/船
gui.flags.minecart.description=&6描述： &a允許在此區域内的玩家/n&a放置和破壞矿车或船/n
gui.flags.fire.name=&e\=> 火的傳播与烧毁
gui.flags.fire.description=&6描述： &a允許火焰在此區域内/n&a傳播并使方块烧成灰烬/n
gui.flags.flow.name=&e\=> 岩浆与水的流動
gui.flags.flow.description=&6描述： &a允許在该區域内/n&a的水和岩浆流動/n
gui.flags.spawn-animals.name=&e\=> 生成動物
gui.flags.spawn-animals.description=&6描述： &a允許在此區域/n&a自然生成動物/n
gui.flags.spawn-monsters.name=&e\=> 生成怪物
gui.flags.spawn-monsters.description=&6描述： &a允許在此區域/n&a自然生成怪物/n
gui.flags.use-potions.name=&e\=> 使用藥水
gui.flags.use-potions.description=&6描述： &a允許玩家向其他人/n&a投掷藥水/n
gui.flags.allow-effects.name=&e\=> 允許效果
gui.flags.allow-effects.description=&6描述： &a允許或取消/n&a所有非此區域/n&a成員的特殊效果
gui.flags.mob-loot.name=&e\=> 允許自爆
gui.flags.mob-loot.description=&6描述： &a允許怪物在此區域内/n&a爆炸/n
gui.flags.flow-damage.name=&e\=> 允許液体破壞
gui.flags.flow-damage.description=&6描述： &a允許水流可以冲毁/n&a各种方块/n
gui.flags.iceform-world.name=&e\=> 允許自然生物的霜冻行走
gui.flags.iceform-world.description=&6描述： &a允許使用霜冻行走/n&a的生物，比如雪人/n&a增加區域内的雪覆盖
gui.flags.iceform-player.name=&e\=> 允許霜冻行走附魔
gui.flags.iceform-player.description=&6描述： &a允許使用霜冻行走附魔/n&a的玩家/n&a在此區域内行走
gui.flags.allow-fly.name=&e\=> 允許飛行
gui.flags.allow-fly.description=&6描述： &a允許可飛行的玩家/n&a&可以在此區域飛行/n
gui.flags.teleport.name=&e\=> 允許傳送
gui.flags.teleport.description=&6描述： &a允許玩家/n&a使用末影珍珠等物品傳送至此/n
gui.flags.clan.name=&e\=> Set Clan Region
gui.flags.clan.description=&bDescription\: &aSet this region as/n&ayour clan home, adding all clan members/n&aat same time with on click.
gui.flags.ender-chest.name=&e\=> 允許用末影箱
gui.flags.ender-chest.description=&6描述： &a允許玩家在该區域内/n&a使用末影箱/n
gui.flags.can-grow.name=&e\=> 允許生長
gui.flags.can-grow.description=&6描述： &a設置该區域内/n&a作物是否可以生長/n
gui.flags.allow-spawner.name=&e\=> 允許与刷怪籠交互
gui.flags.allow-spawner.description=&6描述： &a允許玩家在此區域内/n&a与刷怪籠交互/n
gui.flags.leaves-decay.name=&e\=> 允許葉子枯萎
gui.flags.leaves-decay.description=&6描述： &a允許在此區域内的葉子/n&a自然枯萎/n
gui.flags.build.name=&e\=> 允許建筑
gui.flags.build.description=&6描述： &a允許玩家在此區域内/n&a進行建筑/n
gui.flags.gravity.name=&e=> Allow Block Gravity
gui.flags.gravity.description=&6Description: &aPermits blocks to/n&ahave gravity.
gui.flags.press-plate.name=&e\=> 使用壓力板
gui.flags.press-plate.description=&6描述： &a允許在此區域内的玩家/n&a踩到壓力板上/n
gui.flags.fishing.name=&e=> Allow Fishing
gui.flags.fishing.description=&6Description: &aAllow players to fishing here.
gui.strings.false=&c關
gui.strings.true=&a開
gui.strings.list=&e&l> Open
gui.strings.value=&b設定值\:
gui.strings.separator=&7|
gui.flags.can-back.name=&e=> Allow Back
gui.flags.can-back.description=&6Description: &aAllow players to use/n&a/back command to return/n&ato this region.
gui.flags.can-pet.name=&e=> Allow Pets
gui.flags.can-pet.description=&6Description: &aAllow players to/n&ause pets in this region.
