# +--------------------------------------------------------------------+ #
# <               RedProtect World configuration File                  > #
# <--------------------------------------------------------------------> #
# <       This is the configuration file, feel free to edit it.        > #
# +--------------------------------------------------------------------+ #
# <        You can see the complete commented version of this          > #
# <       configuration file in this link: https://goo.gl/SEbYBZ       > #
# +--------------------------------------------------------------------+ #

config-version: 6.8
# Enable debug messages
debug-messages: false

# Log all commands used by players
log-actions: true

# Available: EN-US, PT-BR, ZH-CN
language: EN-US

# Available: yml and mysql
file-type: yml

# If file-type: yml, configuration:
flat-file:
  # Want to save the regions in your ow files? This can improve performance because theres a new system where the autosave will save only modified regions and not all on auto-save.
  region-per-file: false
  auto-save-interval-seconds: 3600
  backup: true
  max-backups: 10

# If file-type: mysql, configuration:
mysql:
  db-name: redprotect
  user-name: root
  user-pass: redprotect
  host: localhost
  # Regions stay loaded on memory for:
  region-cache-minutes: 2

region-settings:
  # The name of leader for regions created with /rp define. 
  default-leader: '#server#'
  # Colors of world to show on /rp info and /rp list.
  world-colors:
  # Border block type when use /rp border.
  border:
    material: GLOWSTONE
    time-showing: 5
  region-list:
    # Show simple list with only name of region or all region info.
    simple-listing: true
    # If running server 1.8+ enable hover and teleport click on simple list.
    hover-and-click-teleport: true
  # Automatically set max y to 256 and min y to 0 (sky to bedrock).
  autoexpandvert-ondefine: true
  # Deny break/place blocks under chests.
  anti-hopper: true
  # Modes of protection regions
  claim-modes:
    # Default modes for claim regions. Modes available: keep, drop, remove or give. 
    # keep: Nothing happens
    # drop: Will drop all protection blocks
    # remove: Will remove all protection blocks
    # give: Give back the protection blocks to player, and drop(on player location) if players's inventory is full
    mode: keep
    # Allow players to decide what mode to use? If true, the player need to set the line 4 of the sign with [keep], [drop], [remove], [give] or a translation you is using on 'lang.ini'.
    allow-player-decide: false
    # If 'allow-player-decide' is true, player need to have the permission 'redprotect.use-claim-modes' to use modes on signs?
    use-perm: false
  # Limit of blocks/region.
  limit-amount: 8000
  # Limit of claims a player can have.
  claim-amount: 20
  # Block used to protect regions.
  block-id: FENCE
  # Ammount of blocks to scan on place sign to claim a region. Consider this the max area.
  max-scan: 600
  # Time format to use with data and time infos.
  date-format: dd/MM/yyyy
  # Register player visits on... Available: ON-LOGIN, ON-REGION-ENTER.
  record-player-visit-method: ON-LOGIN
  # Allow players without permissions to interact with signs starting with this tags.
  allow-sign-interact-tags:
  - Admin Shop
  - '{membername}'
  # Time in seconds to wait player accept leadership request
  leadership-request-time: 20

# World that player can claim regions.
allowed-claim-worlds:
- example_world

wands:
  # Item used to define and redefine regions.
  adminWandID: 374
  # Item used to check regions.
  infoWandID: 339

private:
  # Enable private signs?
  use: true
  # Allow private signs outside regions
  allow-outside: false
  # Use number IDs instead item names?
  allowed-blocks-use-ids: false
  # Block allowed to lock with private signs.
  allowed-blocks:
  - DISPENSER
  - NOTE_BLOCK
  - BED_BLOCK
  - CHEST
  - WORKBENCH
  - FURNACE
  - JUKEBOX
  - ENCHANTMENT_TABLE
  - BREWING_STAND
  - CAULDRON
  - ENDER_CHEST
  - BEACON
  - TRAPPED_CHEST
  - HOPPER
  - DROPPER

notify:
  # Show region info when enter a region.
  region-enter: true
  # Show region info(or wilderness message) when exit a region.
  region-exit: true
  # How to show the messages? Available: BOSSBAR, CHAT. If plugin BoobarApi not installed, will show on chat.
  region-enter-mode: BOSSBAR
  # Where to show the welcome message (/rp wel <message>)? Available: BOSSBAR, CHAT.
  welcome-mode: BOSSBAR

netherProtection:
  # Max size of your world nether.
  maxYsize: 128
  # Execute this if player go up to maxYsize of nether.
  execute-cmd: 
  - spawn {player}

server-protection:
  # List of potions the player cant use on server. Here the PotioTypes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html
  deny-potions:
  - INVISIBILITY
  # List of causes the player cant die/take damage for. here the list of DamageCauses: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  deny-playerdeath-by:
  - SUFFOCATION
  # Deny certain commands on specific worlds.
  deny-commands-on-worlds:
    world:
    - command
  # Deny players with same nick but cap diferences to join on server (most used on offline severs).
  nickname-cap-filter:
    enabled: false
  # Show all lines of a sign when player place signs in any world.
  sign-spy:
    enabled: false
    # Show only on console or in-game too?
    only-console: true
  teleport-player:
    # Teleport player on join the server.
    on-join:
       enable: false
       # The player need to be in this world to be teleported? Use 'none' for all worlds.
       need-world-to-teleport: none
       # The location, using as world, x, y, z.
       location: world, 0, 90, 0
    # Teleport player on logout the server.
    on-leave:    
       enable: false
       need-world-to-teleport: none
       location: world, 0, 90, 0
  # Deny player to use the item in hand on server.
  deny-item-usage:
    # Allow usage on claimed rps?
    allow-on-claimed-rps: true
    # Allow where no rps?
    allow-on-wilderness: true
    # List of items names.
    items:
    - NONE

# Default values for new regions.
flags:
  pvp: false
  chest: false
  lever: false
  button: false
  door: false
  allow-potions: true
  smart-door: true
  spawn-monsters: true
  spawn-animals: true
  passives: false
  flow: true
  fire: false
  minecart: false
  allow-home: false
  allow-magiccarpet: true
  mob-loot: false
  flow-damage: false

flags-configuration:
  # Duration for timed flags like potions effects, jump, etc.
  effects-duration: 5
  # Flags enabled to players use with commands and flag Gui.
  enabled-flags:
  - pvp
  - chest
  - lever
  - button
  - door
  - smart-door
  - spawn-monsters
  - spawn-animals
  - passives
  - flow
  - fire
  - minecart
  - allow-potions
  - allow-home
  - allow-magiccarpet
  - mob-loot
  - flow-damage
  # Command to use if players with pvp off enter in a region with 'pvparena' enabled.
  pvparena-nopvp-kick-cmd: spawn {player}
  # Delay the player can change a flag after last change.
  change-flag-delay:
    enable: true
    seconds: 10
    # List of flags the player will need to wait to change.
    flags:
    - pvp

# Remove regions after x time the player dont came online.
purge:
  enabled: false
  remove-oldest: 90
  # Hook with WorldEdit, will regen only the region areas to bedrock to sky. Theres no undo for this action!
  regen:
    enable: false
    # Max area size to automatic regen the region.
    max-area-regen: 500
  ignore-regions-from-players:
  
# Put regions to sell after x time the player dont came online.
sell:
  enabled: false
  sell-oldest: 60
  ignore-regions-from-players:
  
# Check for updates?
update-check:
  enable: true
  auto-update: false

performance:
  # DIsable player move event to improve performance? Note: Disabling this will make some flags do not work, like deny enter, execute commands and effects.
  disable-onPlayerMoveEvent-handler: false
  # Disable piston track? Disabling this will allow players to get blocks from protected regions to unprotected.
  disable-PistonEvent-handler: false

hooks:
  essentials:
    # Import last visits from Essentials to RedProtect Regions.
    import-lastvisits: false
  dynmap:
    # Enable hook to show all regions on dynmap plugin?
    enable: true
    # Group to show on hide/show tab map.
    marks-groupname: RedProtect
    # If you use another region mark plugin.
    layer-priority: 10
    # Show names under regions.
    show-label: true
    # Show icons under regions.
    show-icon: true
    # Icon name to show under regions. All icons are available here: http://i.imgur.com/f61GPoE.png
    marker-icon: shield
    min-zoom: 0
    # Default disabled. Set time to check for deleted regions to remove markers in seconds. You dont need to enable this, but dynmap dont have a code to get marker by world, then some icons can persist for deleted regions.
    check-invalid-marks: -1
  magiccarpet:
    # Fix pistons allow get mc blocks.
    fix-piston-getblocks: true
       